# Generated by Django 4.0.2 on 2022-03-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_useraccount_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='bookmarked_tool',
            field=models.ManyToManyField(blank=True, null=True, to='api.Tool'),
        ),
    ]
