# Generated by Django 4.0.2 on 2022-03-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tool_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='categories',
            field=models.ManyToManyField(blank=True, to='api.Category'),
        ),
    ]
