# Generated by Django 4.0.2 on 2022-03-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_useraccount_bookmarked_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='anternative_tool',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='bookmarked_tool',
            field=models.ManyToManyField(blank=True, to='api.Tool'),
        ),
    ]
